import { ActionForm } from "@/components/action-form";
import { pool } from "@/db";
import { formatMoney } from "@/lib/money";
import { playerAction, playerCreditAction } from "@/modules/admin/actions";

export const dynamic = "force-dynamic";
const movementLabel = (value:string)=>({MANUAL:"Ajuste manual",SALE_CREDIT:"Crédito usado no PDV",FUTURE_CHARGE:"Pagamento futuro",FUTURE_PAYMENT:"Recebimento",SALE_REVERSAL:"Estorno de venda"}[value]??value);

export default async function PlayersPage(){
  const [players,movements]=await Promise.all([
    pool.query<{id:string;name:string;email:string|null;phone:string|null;notes:string|null;credit_balance_cents:number;active:boolean}>("SELECT id,name,email,phone,notes,credit_balance_cents,active FROM players ORDER BY active DESC,name"),
    pool.query<{id:string;player_name:string;type:string;amount_cents:number;balance_after_cents:number;sale_id:number|null;notes:string|null;created_at:Date}>(`SELECT m.id,p.name player_name,m.type,m.amount_cents,m.balance_after_cents,m.sale_id,m.notes,m.created_at FROM player_credit_movements m JOIN players p ON p.id=m.player_id ORDER BY m.created_at DESC LIMIT 200`),
  ]);
  return <div className="grid gap-6"><header><p className="text-sm text-gray-500 font-bold">RELACIONAMENTO</p><h1 className="text-3xl font-black">Jogadores e créditos</h1><p className="text-gray-500">Saldo positivo é crédito; saldo negativo representa valor devido pelo jogador.</p></header>
    <ActionForm action={playerAction} className="card p-5 grid md:grid-cols-4 gap-3"><label className="label">Nome<input className="field" name="name" required/></label><label className="label">E-mail<input className="field" type="email" name="email"/></label><label className="label">Telefone<input className="field" name="phone"/></label><label className="label">Observações<input className="field" name="notes"/></label></ActionForm>
    <section className="grid xl:grid-cols-2 gap-4">{players.rows.map(player=><article className="card p-5 grid gap-4" key={player.id}><div className="flex justify-between gap-4"><div><h2 className="font-black text-xl">{player.name}</h2><p className="text-sm text-gray-500">{player.email||"Sem e-mail"} · {player.phone||"Sem telefone"}</p></div><div className="text-right"><small className="text-gray-500">Saldo</small><strong className={`block text-2xl ${player.credit_balance_cents<0?"text-red-600":"text-emerald-700"}`}>{formatMoney(player.credit_balance_cents)}</strong></div></div>
      <ActionForm action={playerCreditAction} className="grid sm:grid-cols-3 gap-2"><input type="hidden" name="playerId" value={player.id}/><label className="label">Operação<select className="field" name="direction"><option value="CREDIT">Adicionar crédito</option><option value="DEBIT">Debitar / criar dívida</option></select></label><label className="label">Valor<input className="field" name="amount" inputMode="decimal" required/></label><label className="label">Motivo<input className="field" name="reason" required/></label></ActionForm>
      <details><summary className="font-bold cursor-pointer">Editar cadastro</summary><ActionForm action={playerAction} className="grid sm:grid-cols-2 gap-2 mt-3"><input type="hidden" name="id" value={player.id}/><label className="label">Nome<input className="field" name="name" defaultValue={player.name}/></label><label className="label">Status<select className="field" name="active" defaultValue={String(player.active)}><option value="true">Ativo</option><option value="false">Inativo</option></select></label><label className="label">E-mail<input className="field" name="email" defaultValue={player.email??""}/></label><label className="label">Telefone<input className="field" name="phone" defaultValue={player.phone??""}/></label><label className="label sm:col-span-2">Observações<input className="field" name="notes" defaultValue={player.notes??""}/></label></ActionForm></details>
    </article>)}{!players.rowCount&&<p className="card p-5">Nenhum jogador cadastrado.</p>}</section>
    <section className="card"><div className="p-5"><h2 className="font-black">Extrato de créditos</h2></div><div className="table-wrap"><table><thead><tr><th>Data</th><th>Jogador</th><th>Tipo</th><th>Venda</th><th>Movimento</th><th>Saldo após</th><th>Observação</th></tr></thead><tbody>{movements.rows.map(m=><tr key={m.id}><td>{m.created_at.toLocaleString("pt-BR",{timeZone:"America/Sao_Paulo"})}</td><td className="font-bold">{m.player_name}</td><td>{movementLabel(m.type)}</td><td>{m.sale_id?`VEN-${String(m.sale_id).padStart(6,"0")}`:"—"}</td><td className={m.amount_cents<0?"text-red-600":"text-emerald-700"}>{m.amount_cents>0?"+":""}{formatMoney(m.amount_cents)}</td><td>{formatMoney(m.balance_after_cents)}</td><td>{m.notes||"—"}</td></tr>)}</tbody></table></div></section>
  </div>;
}
