import { afterAll, beforeAll, describe, expect, it } from "vitest";

const url=process.env.TEST_DATABASE_URL;
const suite=describe.runIf(Boolean(url));
suite("vendas transacionais com PostgreSQL",()=>{
  let pool: typeof import("@/db").pool; let createSale: typeof import("@/modules/sales/service").createSale; let cancelSale: typeof import("@/modules/sales/service").cancelSale;
  let settleFinancialInstallment: typeof import("@/modules/finance/service").settleFinancialInstallment; let createFinancialAccount: typeof import("@/modules/finance/service").createFinancialAccount;
  let operatorId:string,adminId:string,productId:string,playerId:string;
  beforeAll(async()=>{
    if(!url||!new URL(url).pathname.toLowerCase().includes("test"))throw new Error("TEST_DATABASE_URL deve apontar para um banco com 'test' no nome.");
    process.env.DATABASE_URL=url;
    ({pool}=await import("@/db"));({createSale,cancelSale}=await import("@/modules/sales/service"));({settleFinancialInstallment,createFinancialAccount}=await import("@/modules/finance/service"));
    await pool.query("TRUNCATE audit_logs,financial_settlements,financial_installments,player_credit_movements,financial_accounts,stock_movements,payments,sale_items,sales,sessions,products,categories,units,payment_methods,players,users RESTART IDENTITY CASCADE");
    const users=await pool.query<{id:string}>(`INSERT INTO users(name,email,password_hash,role) VALUES ('Admin','admin@test.local','x','ADMIN'),('Operador','op@test.local','x','OPERATOR') RETURNING id,role`);adminId=users.rows[0].id;operatorId=users.rows[1].id;
    await pool.query("INSERT INTO payment_methods(code,name,sort_order) VALUES ('CASH','Dinheiro',0),('PIX','PIX',1),('DEBIT_CARD','Débito',2),('PLAYER_CREDIT','Crédito',3),('FUTURE','Futuro',4)");
    playerId=(await pool.query<{id:string}>("INSERT INTO players(name,credit_balance_cents) VALUES ('Jogador teste',500) RETURNING id")).rows[0].id;
    const unit=await pool.query<{id:string}>("INSERT INTO units(code,name) VALUES ('UN','Unidade') RETURNING id");const cat=await pool.query<{id:string}>("INSERT INTO categories(name) VALUES ('Teste') RETURNING id");
    const product=await pool.query<{id:string}>(`INSERT INTO products(sku,name,category_id,unit_id,cost_cents,sale_price_cents,max_discount_bps,stock_quantity,minimum_stock) VALUES ('T-1','Produto teste',$1,$2,500,900,1000,3,1) RETURNING id`,[cat.rows[0].id,unit.rows[0].id]);productId=product.rows[0].id;
  });
  afterAll(async()=>{await pool?.end()});
  it("persiste venda, snapshot, pagamentos divididos e baixa",async()=>{const sale=await createSale({items:[{productId,quantity:2,discountBasisPoints:500}],payments:[{methodCode:"PIX",amountAppliedCents:1000},{methodCode:"CASH",amountAppliedCents:710,amountReceivedCents:1000}]},operatorId);expect(sale.totalCents).toBe(1710);expect(sale.payments[1].changeCents).toBe(290);const state=await pool.query("SELECT stock_quantity FROM products WHERE id=$1",[productId]);expect(state.rows[0].stock_quantity).toBe(1);const item=await pool.query("SELECT unit_price_cents FROM sale_items WHERE sale_id=$1",[sale.id]);expect(item.rows[0].unit_price_cents).toBe(900);await pool.query("UPDATE products SET sale_price_cents=1200 WHERE id=$1",[productId]);expect(item.rows[0].unit_price_cents).toBe(900);await cancelSale(sale.id,"Cancelamento de teste",adminId);expect((await pool.query("SELECT stock_quantity FROM products WHERE id=$1",[productId])).rows[0].stock_quantity).toBe(3)});
  it("impede desconto acima do limite",async()=>{await expect(createSale({items:[{productId,quantity:1,discountBasisPoints:1100}],payments:[{methodCode:"PIX",amountAppliedCents:1068}]},operatorId)).rejects.toMatchObject({code:"DISCOUNT_LIMIT"})});
  it("serializa duas vendas concorrentes do último item",async()=>{await pool.query("UPDATE products SET stock_quantity=1,sale_price_cents=900 WHERE id=$1",[productId]);const input={items:[{productId,quantity:1,discountBasisPoints:0}],payments:[{methodCode:"PIX",amountAppliedCents:900}]};const results=await Promise.allSettled([createSale(input,operatorId),createSale(input,operatorId)]);expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect(results.filter(r=>r.status==="rejected")).toHaveLength(1);expect((await pool.query("SELECT stock_quantity FROM products WHERE id=$1",[productId])).rows[0].stock_quantity).toBe(0)});
  it("combina crédito do jogador e PIX e reverte no cancelamento",async()=>{await pool.query("UPDATE products SET stock_quantity=2,sale_price_cents=900 WHERE id=$1",[productId]);const sale=await createSale({items:[{productId,quantity:1,discountBasisPoints:0}],payments:[{methodCode:"PLAYER_CREDIT",amountAppliedCents:400,playerId},{methodCode:"PIX",amountAppliedCents:500}]},operatorId);expect((await pool.query("SELECT credit_balance_cents FROM players WHERE id=$1",[playerId])).rows[0].credit_balance_cents).toBe(100);expect((await pool.query("SELECT count(*)::int total FROM player_credit_movements WHERE sale_id=$1",[sale.id])).rows[0].total).toBe(1);await pool.query("UPDATE players SET active=false WHERE id=$1",[playerId]);await cancelSale(sale.id,"Estorno do crédito",adminId);expect((await pool.query("SELECT credit_balance_cents FROM players WHERE id=$1",[playerId])).rows[0].credit_balance_cents).toBe(500);await pool.query("UPDATE players SET active=true WHERE id=$1",[playerId])});
  it("cria recebível futuro, aceita saldo negativo e registra o recebimento",async()=>{await pool.query("UPDATE products SET stock_quantity=2,sale_price_cents=900 WHERE id=$1",[productId]);const sale=await createSale({items:[{productId,quantity:1,discountBasisPoints:0}],payments:[{methodCode:"FUTURE",amountAppliedCents:900,playerId,dueDate:"2026-12-30"}]},operatorId);expect((await pool.query("SELECT credit_balance_cents FROM players WHERE id=$1",[playerId])).rows[0].credit_balance_cents).toBe(-400);const installment=await pool.query<{id:string}>("SELECT i.id FROM financial_installments i JOIN financial_accounts a ON a.id=i.account_id WHERE a.sale_id=$1",[sale.id]);await pool.query("UPDATE players SET active=false WHERE id=$1",[playerId]);await settleFinancialInstallment({installmentId:installment.rows[0].id,amountCents:900,methodCode:"PIX",occurredAt:"2026-10-09T12:00",personName:"Jogador teste"},adminId);expect((await pool.query("SELECT credit_balance_cents FROM players WHERE id=$1",[playerId])).rows[0].credit_balance_cents).toBe(500);expect((await pool.query("SELECT status FROM financial_accounts WHERE sale_id=$1",[sale.id])).rows[0].status).toBe("SETTLED");await expect(cancelSale(sale.id,"Já foi recebido",adminId)).rejects.toMatchObject({code:"FUTURE_ALREADY_SETTLED"});await pool.query("UPDATE players SET active=true WHERE id=$1",[playerId])});
  it("divide uma conta em prazos 30/60/90 preservando os centavos",async()=>{const id=await createFinancialAccount({type:"PAYABLE",description:"Compra parcelada",counterpartyName:"Distribuidor",issueDate:"2026-10-09",totalCents:10000,terms:"30/60/90"},adminId);const installments=await pool.query("SELECT due_date::text,amount_cents FROM financial_installments WHERE account_id=$1 ORDER BY installment_number",[id]);expect(installments.rows.map(row=>row.due_date)).toEqual(["2026-11-08","2026-12-08","2027-01-07"]);expect(installments.rows.reduce((sum,row)=>sum+row.amount_cents,0)).toBe(10000)});
});
