import Link from "next/link";
import { pool } from "@/db";
import { formatMoney, saleNumber } from "@/lib/money";
export const dynamic = "force-dynamic";
export default async function SalesPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const q=await searchParams; const values:unknown[]=[]; const where:string[]=[];
  if(q.from){values.push(q.from);where.push(`s.created_at >= $${values.length}::date`)} if(q.to){values.push(q.to);where.push(`s.created_at < $${values.length}::date + interval '1 day'`)} if(q.operator){values.push(q.operator);where.push(`s.operator_id=$${values.length}`)} if(q.status){values.push(q.status);where.push(`s.status=$${values.length}`)} if(q.payment){values.push(q.payment);where.push(`EXISTS(SELECT 1 FROM payments px WHERE px.sale_id=s.id AND px.method_code=$${values.length})`)}
  const [sales,operators,methods]=await Promise.all([pool.query(`SELECT s.id,s.created_at,s.total_cents,s.status,u.name operator,string_agg(pm.name,', ' ORDER BY pm.sort_order) payments FROM sales s JOIN users u ON u.id=s.operator_id JOIN payments p ON p.sale_id=s.id JOIN payment_methods pm ON pm.code=p.method_code ${where.length?`WHERE ${where.join(" AND ")}`:""} GROUP BY s.id,u.name ORDER BY s.created_at DESC LIMIT 200`,values),pool.query("SELECT id,name FROM users ORDER BY name"),pool.query("SELECT code,name FROM payment_methods ORDER BY sort_order")]);
  return <div className="grid gap-5"><header><p className="text-sm text-gray-500 font-bold">RELATÓRIOS</p><h1 className="text-3xl font-black">Vendas</h1></header><form className="card p-4 grid sm:grid-cols-2 xl:grid-cols-6 gap-3 items-end"><label className="label">De<input className="field" type="date" name="from" defaultValue={q.from}/></label><label className="label">Até<input className="field" type="date" name="to" defaultValue={q.to}/></label><label className="label">Operador<select className="field" name="operator" defaultValue={q.operator??""}><option value="">Todos</option>{operators.rows.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label><label className="label">Pagamento<select className="field" name="payment" defaultValue={q.payment??""}><option value="">Todos</option>{methods.rows.map(m=><option value={m.code} key={m.code}>{m.name}</option>)}</select></label><label className="label">Status<select className="field" name="status" defaultValue={q.status??""}><option value="">Todos</option><option value="CONFIRMED">Confirmada</option><option value="CANCELED">Cancelada</option></select></label><button className="btn btn-primary">Filtrar</button></form><section className="card table-wrap"><table><thead><tr><th>Número</th><th>Data</th><th>Operador</th><th>Pagamento</th><th>Total</th><th>Status</th><th></th></tr></thead><tbody>{sales.rows.map(s=><tr key={s.id}><td className="font-bold">{saleNumber(s.id)}</td><td>{new Date(s.created_at).toLocaleString("pt-BR")}</td><td>{s.operator}</td><td>{s.payments}</td><td>{formatMoney(s.total_cents)}</td><td><span className={`badge ${s.status==="CONFIRMED"?"badge-ok":"badge-danger"}`}>{s.status==="CONFIRMED"?"Confirmada":"Cancelada"}</span></td><td><Link className="font-bold text-blue-700" href={`/admin/sales/${s.id}`}>Detalhes</Link></td></tr>)}</tbody></table></section></div>;
}
