import { pool } from "@/db";
import { ActionForm } from "@/components/action-form";
import { stockAction } from "@/modules/admin/actions";
export const dynamic = "force-dynamic";
const movementLabel: Record<string,string>={INITIAL:"Estoque inicial",MANUAL_IN:"Entrada manual",MANUAL_ADJUSTMENT:"Ajuste",RETURN:"Devolução",SALE:"Venda",SALE_CANCELLATION:"Cancelamento"};
export default async function StockPage({ searchParams }: { searchParams: Promise<{ status?: string }> }) {
  const status=(await searchParams).status??"all";
  const condition=status==="empty"?"AND p.stock_quantity=0":status==="low"?"AND p.stock_quantity>0 AND p.stock_quantity<=p.minimum_stock":"";
  const [products,movements]=await Promise.all([pool.query(`SELECT p.id,p.sku,p.name,p.stock_quantity,p.minimum_stock FROM products p WHERE p.active=true ${condition} ORDER BY p.name`),pool.query(`SELECT sm.id,sm.type,sm.quantity_delta,sm.previous_quantity,sm.new_quantity,sm.notes,sm.created_at,p.name product,u.name username FROM stock_movements sm JOIN products p ON p.id=sm.product_id JOIN users u ON u.id=sm.user_id ORDER BY sm.created_at DESC LIMIT 100`)]);
  const allProducts=condition?await pool.query("SELECT id,sku,name FROM products WHERE active=true ORDER BY name"):products;
  return <div className="grid gap-5"><header><p className="text-sm text-gray-500 font-bold">INVENTÁRIO</p><h1 className="text-3xl font-black">Estoque</h1></header><ActionForm action={stockAction} className="card p-4 grid md:grid-cols-2 xl:grid-cols-5 gap-3 items-end"><label className="label xl:col-span-2">Produto<select className="field" name="productId">{allProducts.rows.map(p=><option value={p.id} key={p.id}>{p.sku} — {p.name}</option>)}</select></label><label className="label">Tipo<select className="field" name="type"><option value="MANUAL_IN">Entrada</option><option value="MANUAL_ADJUSTMENT">Ajuste (+/-)</option><option value="RETURN">Devolução</option></select></label><label className="label">Quantidade<input className="field" name="quantity" type="number" required/></label><label className="label">Motivo<input className="field" name="notes" minLength={5} required/></label></ActionForm><nav className="flex gap-2"><a className="btn btn-ghost" href="/admin/stock">Todos</a><a className="btn btn-ghost" href="?status=low">Baixo</a><a className="btn btn-ghost" href="?status=empty">Sem estoque</a></nav><section className="card table-wrap"><table><thead><tr><th>SKU</th><th>Produto</th><th>Atual</th><th>Mínimo</th><th>Situação</th></tr></thead><tbody>{products.rows.map(p=><tr key={p.id}><td>{p.sku}</td><td className="font-bold">{p.name}</td><td>{p.stock_quantity}</td><td>{p.minimum_stock}</td><td><span className={`badge ${p.stock_quantity===0?"badge-danger":p.stock_quantity<=p.minimum_stock?"badge-warn":"badge-ok"}`}>{p.stock_quantity===0?"Sem estoque":p.stock_quantity<=p.minimum_stock?"Baixo":"Normal"}</span></td></tr>)}</tbody></table></section><section className="card"><h2 className="font-black p-5">Últimas movimentações</h2><div className="table-wrap"><table><thead><tr><th>Data</th><th>Produto</th><th>Tipo</th><th>Variação</th><th>Saldo</th><th>Usuário</th><th>Observação</th></tr></thead><tbody>{movements.rows.map(m=><tr key={m.id}><td>{new Date(m.created_at).toLocaleString("pt-BR")}</td><td>{m.product}</td><td>{movementLabel[m.type]}</td><td className={m.quantity_delta>0?"text-emerald-700":"text-red-700"}>{m.quantity_delta>0?"+":""}{m.quantity_delta}</td><td>{m.previous_quantity} → {m.new_quantity}</td><td>{m.username}</td><td>{m.notes}</td></tr>)}</tbody></table></div></section></div>;
}
